### ISSUE TITLE
拡張機能更新時に表示される更新情報のリンクが切れている

### ISSUE THREAD

**Issue by den3asphalt** [scombz-utilities/scombz-utilities-react#124]
修正済みだったらごめんなさい

**Comment by yudai1204** [comment]
`scombz-utilities.com/release/[version]/`のリンクが切れているということでしょうか？
リリースノート未作成のバージョンのリンクを指定した場合は、404になるのが正常です。

**Comment by den3asphalt** [comment]
> `scombz-utilities.com/release/[version]/`のリンクが切れているということでしょうか？ リリースノート未作成のバージョンのリンクを指定した場合は、404になるのが正常です。

DEVの方を再読み込みしたときscombz-utilities.com/updates.htmlに飛んだのでおかしいなあと思ってPRを出したのですが、単に読み込むファイルを間違えていたようでした。
お騒がせして申し訳ないです。
