### ISSUE TITLE
設定項目の整理

### ISSUE THREAD

**Issue by newt239** [scombz-utilities/scombz-utilities-react#59]
設定項目が多すぎるため、いくつかの設定の統合及び廃止（デフォルトで有効化）を提案します。
基本的には「このオプションを個別に変更したいユースケースが思いつかない」という基準でピックアップしました。
廃止した機能については新たに全機能を一覧できるページを作り、そこに載せる形にするのが分かりやすいと思います。

| No. | 種別 | ID | 分類 |
| ---- | ---- | ---- | ---- |
| 1 | 統合 | clickLogin, autoAdfs | 基本設定 |
| 2 | 廃止 | displayTime | 時間割ウィジェット |
| 3 | 廃止 | highlightToday | 時間割ウィジェット |
| 4 | 廃止 | markdownNotePad | 科目ページ |
| 5 | 廃止 | layout.linkify | 科目ページ |
| 6 | 廃止 | sortSubjectByOrder | 科目ページ |
| 7 | 廃止 | dragAndDropBugFix | 課題提出ページ |
| 8 | 廃止 | lms.showClassroom | LMSページ |
| 9 | 廃止 | downloadFileBundle | 授業ページ |

**Comment by yudai1204** [comment]
ありがとうございます！
統合できるものを除いて、基本的に設定だけで全体を把握できるようにしたいというのと、ScombZ自体の仕様変更に設定だけで一時的にでも対処できるようにさせたいというのがあり、なるべく廃止はしたくないんですよね（奥まったところに入れるというのはアリかも）。
検証すべき点について思いついたものを載せておきます。

#### clickLogin
- ログインボタン自動クリックをすると、以下の以下の画像のような「お知らせ」が見られないという問題があります。
- 統合する場合は、これらを自動取得した上でScombZ内からも見えるようにしておくと良さそう？
  - 自動取得自体はしていた気がします (`saves.scombzData.beforeLoginOshirase`)。
  - でも↑がちゃんと動いているかは不明。

| ログイン前にのみ閲覧可能なお知らせ |
|-|
| <img width="400" alt="スクリーンショット 2024-05-17 18 00 56" src="https://github.com/scombz-utilities/scombz-utilities-react/assets/59430508/e1e8fa0f-5e50-496c-a9aa-bf8a1adbd95d"> |

#### displayTime
これは廃止しても良いかもしれないですね。

#### highlightToday
- オフにしたい人、いないかな、、、(ウィジェットだけでなく、この設定はLMSページの時間割にも影響します)

#### markdownNotePad, layout.linkify, sortSubjectByOrder, dragAndDropBugFix, downloadFileBundle
- 機能自体が影響する範囲が大きいので、強制ONだとScombZの仕様変更にユーザが対応しきれないかもしれません。
- 特に、sortSubjectByOrderは影響範囲が大きそうです(既存のDOM自体の順番を入れ替える操作をしているため)。
- ただし、sortSubjectByOrderはsubjectOrderと統合できそうですね。

#### lms.showClassroom
- これは個人的には微妙なラインです（削除しても今のままでも良いかも...）
- ただし、英語設定かつ表示する教室数がとても多い場合に表示がはみ出るというバグを確認しています。
  - scombz標準のtoolboxで教室表示する際も英語でははみ出ているので放置しています

| 表示崩れ |
|-|
| <img width="400" alt="スクリーンショット 2024-05-17 18 19 07" src="https://github.com/scombz-utilities/scombz-utilities-react/assets/59430508/c4c5eb7b-f2ad-43d3-a750-1356d25e992e"> |

**Comment by yudai1204** [comment]
開発者向けオプションは良いアイデアですね。
一旦それで様子を見てみると良さそうに思います！
catchでエラーを補足したらDOM変更しないみたいな感じにすると良さそうですね
sortSubjectByOrderについても、それで良さそうに見えます！

**Comment by newt239** [comment]
> catchでエラーを補足したらDOM変更しないみたいな感じにすると良さそうですね

ですです、なんならついでにDiscordとかにクラッシュログをリポートしても良いかも？

とりあえず説明文改善作業がある程度進んだら開発者向けオプション作っちゃいます！

**Comment by yudai1204** [comment]
クラッシュレポートなどを送信するとなると、プライバシーポリシーを変える必要がありそうなので、要検討ですね
Chromeの規約上、外部にデータを送信する場合はプライバシーポリシーの明示が必須なんですよね

開発者向けオプションはぜひお願いします！
