### ISSUE TITLE
自作課題が追加できない

### ISSUE THREAD

**Issue by den3asphalt** [scombz-utilities/scombz-utilities-react#82]
DMの方でバグ報告が来たので取り急ぎご報告。

自作課題入力画面において、課題URL、課題名、科目URLは入力済みで科目名だけ埋まっていない状態で、科目欄を表示される項目から選択すると、枠が急に閉じられる。

**Comment by yudai1204** [comment]
私の環境では再現できず...
環境依存だったら嫌だな

**Comment by den3asphalt** [comment]
> 私の環境(Mac Chrome stable, Win chrome stable)では再現できず...
> 環境依存だったら嫌だな
> 
> 追記：動作がEscキーを押し下げた時に起こるものと類似していそうなので、Escキーを押しているかを確認してほしい

こちら、報告者の勘違いで、再起動したら直ったようです。
ご迷惑をおかけしました🙇
