### ISSUE TITLE
自作課題のURLが正しくない

### ISSUE THREAD

**Issue by den3asphalt** [scombz-utilities/scombz-utilities-react#83]
これも取り急ぎDMから。
本当にごめん
![i4M4a7Mx](https://github.com/scombz-utilities/scombz-utilities-react/assets/86176261/34ff4ddd-9adc-4ae4-9cf0-7b811980bbb0)

**Comment by yudai1204** [comment]
こちらも私の環境では再現ができず...
popupから開いたのか、一覧から開いたのかによって動作が違うのは既知で修正予定なんですが、どちらで開いたかを追記していただけると、、、

**Comment by den3asphalt** [comment]
助かりました，ありがとうございます…
