### ISSUE TITLE
常に名前を非表示

### ISSUE THREAD

**Issue by den3asphalt** [scombz-utilities/scombz-utilities-react#95]
クリックで消すのではなく、常に名前を消しておきたい。
legacyにおける「履修者名表示機能」の実装

**Comment by yudai1204** [comment]
refactor以降、数行のCSSで代替できる機能を1つの設定項目として増やすことは肥大化に繋がるため避けようと考えています。
そのため、他の機能と設定をまとめる事は難しいかつ数行のカスタムCSSでやりたいことを実現可能であるこの機能は不要であると考えます。

**Comment by den3asphalt** [comment]
> refactor以降、数行のCSSで代替できる機能を1つの設定項目として増やすことは肥大化に繋がるため避けようと考えています。 そのため、他の機能と設定をまとめる事は難しいかつ数行のカスタムCSSでやりたいことを実現可能であるこの機能は不要であると考えます。
> 
> 関連issue: #59

なるほど、了解です。そういう方針なら提案を取り下げます。
